### ISSUE TITLE
compatibility for HASS .0.89

### ISSUE THREAD

**Issue by thundergreen** [biker91620/ha-cozytouch#3]
Will you update this custom component to make it compatible to new hass version ?

Would be nice jst having a feedback

thanks :)

**Comment by biker91620** [comment]
I will update this component as soon as possible :)

**Comment by thundergreen** [comment]
Greta! Thanks a lot!

Gesendet von Mail für Windows 10

Von: biker91620
Gesendet: Montag, 11. März 2019 13:20
An: biker91620/ha-cozytouch
Cc: ThUnD3r|Gr33n; Author
Betreff: Re: [biker91620/ha-cozytouch] compatibility for HASS .0.89 (#3)

I will update this component as soon as possible :)

**Comment by biker91620** [comment]
Well done :)
