### ISSUE TITLE
compatibility with latest release 0.96

### ISSUE THREAD

**Issue by thundergreen** [biker91620/ha-cozytouch#7]
Dear my friend . Die to rewrite of climate component this cc won't work anymore 

Would it be possible to check this?

Thanks in advance

**Comment by biker91620** [comment]
Working on it.
Will be compatible with latest release 0.98.3 .

**Comment by thundergreen** [comment]
Will you also make a hacs implementation? :: great man! I am glad to hear that you are still maintaining this awesome component :)

**Comment by browetd** [comment]
Great news !  I can test it if needed...

**Comment by biker91620** [comment]
I rewrited components. 
It work with the latest release (not hass.io yet).
Your feedback are welcome.
