### ISSUE TITLE
Occupancy Sensors are always "Off"

### ISSUE THREAD

**Issue by Sku4l** [biker91620/ha-cozytouch#9]
Running here on hass v0.97 and latest version of cozypy.

I noticed that the occupancysensors on my Thermor Ovation 3 heaters were never triggered. This seems to be due to an error in the cozypy component (which looks for "PersonInside" instead of "personInside").

I proposed a commit change in the cozypy component github, I hope I did not do anything wrong because this is the first time I use GitHub.

**Comment by biker91620** [comment]
Thanks for your feedback.
I solved this issue on CozyPy library.
I'm updating my custom components to support Hass v0.98.3 
The occupancy sensors fix will be in next release :)
